server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
            enable-dlq: true
            dlq-name: send-communication-dlq
        emailsms-out-0:
          destination: communication-sent
          producer:
            use-native-encoding: true
      kafka:
        binder:
          brokers:
            - ${KAFKA_BROKERS:localhost:9092}
          consumer-properties:
            schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
            specific.avro.reader: true
          producer-properties:
            schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
            auto.register.schemas: true